// Generated from src/tokens.json. Do not edit this file directly.
import SwiftUI

enum YYStudioTokens {
  static let ground = Color(hex: "#FFFFFF")
  static let ink = Color(hex: "#242220")
  static let muted = Color(hex: "#55534E")
  static let quiet = Color(hex: "#6D6A63")
  static let hairline = Color(hex: "#E4E1DC")
  static let controlRadius: CGFloat = 10
  static let panelRadius: CGFloat = 18
  static let modalRadius: CGFloat = 26
  static let quick: Double = 0.15
  static let fast: Double = 0.25
  static let medium: Double = 0.35
  static let slow: Double = 0.40
  static let easeOut = Animation.timingCurve(0.22, 1, 0.36, 1, duration: fast)
}

extension Color {
  init(hex: String) {
    let value = UInt64(hex.dropFirst(), radix: 16) ?? 0
    self.init(.sRGB, red: Double((value >> 16) & 255) / 255, green: Double((value >> 8) & 255) / 255, blue: Double(value & 255) / 255, opacity: 1)
  }
}
